[workspace]

members = [
    "algebra",
    "algebra_derive",
    "bool",
    "fhe_core",
    "lattice",
    "network",
]

resolver = "2"

[workspace.dependencies]
thiserror = "1.0"
num-traits = "0.2"
once_cell = "1.19"
rand = "0.8"
rand_distr = "0.4"
rand_core = "0.6.4"
rand_chacha = "0.3.1"
rayon = "1"
bytemuck = { version = "1.13", features = ["derive"] }
merlin = { version = "3.0.0", default-features = false }
serde = { version = "1.0", features = ["derive"] }
bincode = "1.3"
itertools = "0.13"
sha2 = { version = "0.10" }
mimalloc = "0.1"

criterion = "0.5"

# For network
grpcio = "0.7"
protobuf = { version = "2.*.*", features = ["with-bytes"] }
protobuf-codegen = "2.*.*"
protoc = "2.*.*"

anyhow = "1.0"
futures = { version = "0.3", features = ["thread-pool", "compat"] }
futures-executor = "0.3.1"
futures-timer = "3.0"
futures-util = { version = "0.3.1", default-features = false, features = [
    "io",
    "async-await",
] }

structopt = "0.3.20"
log = "0.4"
pretty_env_logger = "0.4"


# for io
crossbeam = "0.8"
crossbeam-channel = "0.5"

serde_json = "1.0"

[profile.bench]
lto = true
codegen-units = 1

[profile.release]
lto = true
codegen-units = 1
