[workspace]

members = ["algebra", "boolean_fhe", "fhe_core", "lattice"]

resolver = "2"

[workspace.dependencies]
thiserror = "2"
num-traits = "0.2"
rand = "0.8"
rand_distr = "0.4"
itertools = "0.14"

criterion = "0.5"

[profile.bench]
lto = true
codegen-units = 1
