[package]
name = "fhe_core"
version = "0.1.0"
edition = "2021"

[dependencies]
algebra = { path = "../algebra" }
lattice = { path = "../lattice" }

thiserror = { workspace = true }
num-traits = { workspace = true }
rand = { workspace = true }
rand_chacha = "0.3.1"
once_cell = { workspace = true }
serde = { workspace = true }

[features]
default = []
nightly = ["algebra/nightly", "lattice/nightly"]
