[package]
name = "mpc"
version = "0.1.0"
edition = "2021"

[dependencies]
algebra = { version = "0.1.0", path = "../algebra" }
network = { version = "0.1.0", path = "../network" }
rand.workspace = true
rand_core.workspace = true
bytemuck = "1.22.0"
crossbeam = "0.8.4"
