[package]
name = "algebra"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
algebra_derive = { path = "../algebra_derive" }

thiserror = "1.0"

num-traits = "0.2"

rand = "0.8"
rand_distr = "0.4"

once_cell = "1.18"

[features]
default = []

[dev-dependencies]
criterion = "0.5"

[[bench]]
name = "ntt_bench"
harness = false

[package.metadata.docs.rs]
all-features = true
# enable unstable features in the documentation
rustdoc-args = ["--cfg", "docsrs"]
# RUSTDOCFLAGS="--cfg docsrs" cargo +nightly doc --all-features --no-deps
