//! Interactive Proof Protocol used for Multilinear Sumcheck
// It is derived from https://github.com/arkworks-rs/sumcheck/blob/master/src/ml_sumcheck/protocol/mod.rs.

use algebra::{Field, ListOfProductsOfPolynomials, PolynomialInfo};
use prover::{ProverMsg, ProverState};
use std::marker::PhantomData;
use verifier::SubClaim;
pub mod prover;
pub mod verifier;
use algebra::utils::Transcript;

/// IP for MLSumcheck   
pub struct IPForMLSumcheck<F: Field> {
    _marker: PhantomData<F>,
}

/// Sumcheck for products of multilinear polynomial
pub struct MLSumcheck<F: Field>(PhantomData<F>);

/// proof generated by prover
pub type Proof<F> = Vec<ProverMsg<F>>;

impl<F: Field> MLSumcheck<F> {
    /// Extract sum from the proof
    pub fn extract_sum(proof: &Proof<F>) -> F {
        proof[0].evaluations[0] + proof[0].evaluations[1]
    }

    /// Generate proof of the sum of polynomial over {0, 1}^`num_vars`
    ///
    /// The polynomial is represented by a list of products of polynomials along with its coefficient that is meant to be added together.
    ///
    /// This data structure of the polynomial is a list of list of `(coefficient, DenseMultilinearExtension)`.
    /// * Number of products n = `polynomial.products.len()`,
    /// * Number of multiplicands of ith product m_i = `polynomial.products[i].1.len()`,
    /// * Coefficient of ith product c_i = `polynomial.products[i].0`
    ///
    /// The resulting polynomial is
    ///
    /// $$\sum_{i=0}^{n}C_i\cdot\prod_{j=0}^{m_i}P_{ij}$$
    pub fn prove(
        polynomial: &ListOfProductsOfPolynomials<F>,
    ) -> Result<Proof<F>, crate::error::Error> {
        let mut trans = Transcript::<F>::new();
        Self::prove_as_subprotocol(&mut trans, polynomial).map(|r| r.0)
    }

    /// This function does the same thing as `prove`, but it uses a `Fiat-Shamir RNG` as the transcript/to generate the
    /// verifier challenges. Additionally, it returns the prover's state in addition to the proof.
    /// Both of these allow this sumcheck to be better used as a part of a larger protocol.
    pub fn prove_as_subprotocol(
        trans: &mut Transcript<F>,
        polynomial: &ListOfProductsOfPolynomials<F>,
    ) -> Result<(Proof<F>, ProverState<F>), crate::error::Error> {
        trans.feed(b"polynomial info", &polynomial.info());

        let mut prover_state = IPForMLSumcheck::prover_init(polynomial);
        let mut verifier_msg = None;
        let mut prover_msgs = Vec::with_capacity(polynomial.num_variables);
        for _ in 0..polynomial.num_variables {
            let prover_msg = IPForMLSumcheck::prove_round(&mut prover_state, &verifier_msg);
            trans.feed(b"sumcheck msg", &prover_msg);
            prover_msgs.push(prover_msg);

            verifier_msg = Some(IPForMLSumcheck::sample_round(
                &mut trans.rng(b"sumcheck randomness"),
            ));
        }
        prover_state
            .randomness
            .push(verifier_msg.unwrap().randomness);
        Ok((prover_msgs, prover_state))
    }

    /// verify the proof using `polynomial_info` as the verifier key
    pub fn verify(
        polynomial_info: &PolynomialInfo,
        claimed_sum: F,
        proof: &Proof<F>,
    ) -> Result<SubClaim<F>, crate::Error> {
        let mut trans = Transcript::<F>::new();
        Self::verify_as_subprotocol(&mut trans, polynomial_info, claimed_sum, proof)
    }

    /// This function does the same thing as `verify`, but it uses a `Fiat-Shamir RNG`` as the transcript to generate the
    /// verifier challenges. This allows this sumcheck to be used as a part of a larger protocol.
    pub fn verify_as_subprotocol(
        trans: &mut Transcript<F>,
        polynomial_info: &PolynomialInfo,
        claimed_sum: F,
        proof: &Proof<F>,
    ) -> Result<SubClaim<F>, crate::Error> {
        // let mut trans = Transcript::<F>::new();
        trans.feed(b"polynomial info", polynomial_info);

        let mut verifier_state = IPForMLSumcheck::verifier_init(polynomial_info);
        for i in 0..polynomial_info.num_variables {
            let prover_msg = proof.get(i).expect("proof is incomplete");
            trans.feed(b"sumcheck msg", prover_msg);

            IPForMLSumcheck::verify_round(
                (*prover_msg).clone(),
                &mut verifier_state,
                &mut trans.rng(b"sumcheck randomness"),
            );
        }

        IPForMLSumcheck::check_and_generate_subclaim(verifier_state, claimed_sum)
    }
}
