name: Security audit

on:
  # Run manually
  workflow_dispatch:
  schedule:
    - cron: "0 19 * * 5"
  push:
    paths:
      # Run if workflow changes
      - ".github/workflows/security.yml"
      # Run on changed dependencies
      - "**/Cargo.toml"
      - "**/Cargo.lock"

permissions: read-all

jobs:
  security_audit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: rustsec/audit-check@v1.4.1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
