name: Security audit

on:
  # Run manually
  workflow_dispatch:
  schedule:
    - cron: "0 19 * * 5"
  push:
    paths:
      # Run if workflow changes
      - ".github/workflows/security.yml"
      # Run on changed dependencies
      - "**/Cargo.toml"
      - "**/Cargo.lock"

permissions: read-all

jobs:
  audit:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      issues: write
    steps:
      - uses: actions/checkout@v4
      - uses: actions-rust-lang/audit@v1
        name: Audit Rust Dependencies
        with:
          TOKEN: ${{ secrets.GITHUB_TOKEN }}
